debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.kia.backend: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
