debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.kia.assignment: debug
    org.springframework.web.servlet: debug

spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
